name = "odin"
main = "src/index.ts"
compatibility_date = "2025-03-24"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_URL = "https://odin.prismwalls.workers.dev"
ENCRYPTION_METADATA_KEY = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "odin-files"
preview_bucket_name = "odin-files-preview"

[[kv_namespaces]]
binding = "KV_METADATA"
id = "941ae40d709d46d59869d16be3fe00ad"
preview_id = "fdc4d514be384d9d932b85b01ad5c568"

[triggers]
crons = ["0 * * * *"]
